- name: install ec2 and r53
  host: local
  connection: local
  vars:
    subnet_id:
    sg_id:
    zone:
    ami_id:
    instances:
      - mysql
      - backend
      - frontend
  tasks:
  - name: ansible to install boto3 and botocore
    ansible.builtin.pip:
      name:
      - boto3
      - botocore
      executable: pip3.9

  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      instance_type: "t3.micro"
    loop: "{{ instances }}"
    register: ec2_incstances
    
  - name: print the oputput
    ansible.builtin.debug:
      msg: "{{ ec2_instances}}"

